admins = ["76561198090501821", "76561198033132614", "76561198061044473"]

[discord]
id = "298249897973383168"
secret = "h-x_nA0NSONJpjRmXGQVq7GzKUEt1uQa"
callback = "http://rusher.lt.imsean.me/auth/discord/callback"

[steam]
apiKey = "7B41488FCE3598BC40659CD8E55D0964"
realm = "http://rusher.lt.imsean.me/"
callback = "http://rusher.lt.imsean.me/auth/steam/callback"

[session]
secret = "rushersdiscord" # make sure this is random

[mongodb]
host = "localhost"
port = 27017
db = "rushersdiscord"

[billing]
sandbox = false
cipherSecret = "foobarbazqux" # DO NOT LOSE THIS.

  [billing.api]
  username = "sales_api1.thestrivestore.com"
  password = "DM7T3MJGWNUBGWHL"
  signature = "AFcWxV21C7fd0v3bYYYRCpSSRl31AcF9-DtrIwNdQagMgSb-vJzf-Mwh"

[plans]

  [plans.gold]
  name = "Gold"
  price = 5.00
  features = [
    "Access to \"Video Suggestions for Rusher\" text channel",
  ]
  itemNumber = "300529382580289537"
  buttonID = "RA5DQTDBDVLQC"

  [plans.champion]
  name = "Champion"
  price = 25.00
  features = [
    "Can enter in a weekly lottery to play and talk with TheCampingRusher each Sunday",
    "Access to \"Video Suggestions for Rusher\" text channel",
    "Listen in on videos at any time",
  ]
  best = true
  itemNumber = "300529352821440514"
  buttonID = "HK6HK6ESURLY4"

  [plans.platinum]
  name = "Platinum"
  price = 10.00
  features = [
    "Listen in on videos at any time",
    "Access to \"Video Suggestions for Rusher\" text channel",
  ]
  itemNumber = "300529406986682368"
  buttonID = "K6GSN8M855HSU"

[bot]
guild = "300529317992071168"
logChannel = "300529317992071168"
confirmChannel = "302701901143867393"
confirmMessage = "Thanks for purchasing {{item}}, {{userMention}}!\nWe really appreciate it"
token = "Mjk4MjQ5ODk3OTczMzgzMTY4.C9P4ZA.rQz2rG0R5ftNIZNaClROdQNyMOo"
inviteCode = "dka4rUx"
